import type { Store, Mission, User, Review, Reward, Badge } from '@/types'

export const mockStores: Store[] = [
  {
    id: 'store-1',
    name: 'Ristr8to Lab',
    slug: 'ristr8to-lab',
    description: 'Award-winning specialty coffee lab in the heart of Nimman. Known for their innovative brewing methods and single-origin beans sourced from Northern Thai highlands.',
    category: 'cafe',
    subcategory: 'specialty coffee',
    location: 'Nimmanhaemin Rd, Suthep, Mueang Chiang Mai',
    latitude: 18.7953,
    longitude: 98.9673,
    images: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
      'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800',
    ],
    phone: '+66 53 215 278',
    website: 'https://ristr8to.com',
    crowdLevel: 'MODERATE',
    averageRating: 4.8,
    totalVisitors: 12450,
    weeklyVisitors: 280,
    isApproved: true,
    isFeatured: true,
    isHiddenGem: false,
    ownerId: 'user-merchant-1',
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'store-2',
    name: 'Khao Soi Lung Prakit',
    slug: 'khao-soi-lung-prakit',
    description: 'Legendary Khao Soi spot beloved by locals for over 30 years. The rich coconut curry broth is made from a secret family recipe passed down three generations.',
    category: 'restaurant',
    subcategory: 'northern thai',
    location: 'Faham Rd, Mueang Chiang Mai',
    latitude: 18.7871,
    longitude: 98.9847,
    images: [
      'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
      'https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=800',
    ],
    crowdLevel: 'BUSY',
    averageRating: 4.9,
    totalVisitors: 34200,
    weeklyVisitors: 650,
    isApproved: true,
    isFeatured: true,
    isHiddenGem: false,
    ownerId: 'user-merchant-2',
    createdAt: '2024-01-10T08:00:00Z',
  },
  {
    id: 'store-3',
    name: 'Woo Cafe & Art Gallery',
    slug: 'woo-cafe-art-gallery',
    description: 'A charming blend of contemporary art and artisan coffee. Set inside a beautifully restored lanna-style house with rotating exhibitions from local artists.',
    category: 'cafe',
    subcategory: 'art cafe',
    location: 'Charoen Rat Rd, Wat Ket, Mueang Chiang Mai',
    latitude: 18.7804,
    longitude: 98.9984,
    images: [
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
    ],
    crowdLevel: 'QUIET',
    averageRating: 4.6,
    totalVisitors: 5200,
    weeklyVisitors: 85,
    isApproved: true,
    isFeatured: false,
    isHiddenGem: true,
    ownerId: 'user-merchant-3',
    createdAt: '2024-02-01T08:00:00Z',
  },
  {
    id: 'store-4',
    name: 'Zoe in Yellow',
    slug: 'zoe-in-yellow',
    description: 'The heartbeat of Chiang Mai nightlife. This vibrant bar transforms into a dance haven after dark with live DJs, craft cocktails, and an electric atmosphere.',
    category: 'bar',
    subcategory: 'nightlife',
    location: 'Ratchawithee Rd, Si Phum, Mueang Chiang Mai',
    latitude: 18.7900,
    longitude: 98.9924,
    images: [
      'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
    ],
    crowdLevel: 'VERY_BUSY',
    averageRating: 4.3,
    totalVisitors: 28100,
    weeklyVisitors: 920,
    isApproved: true,
    isFeatured: true,
    isHiddenGem: false,
    ownerId: 'user-merchant-4',
    createdAt: '2024-01-20T08:00:00Z',
  },
  {
    id: 'store-5',
    name: 'Baan Kang Wat Market',
    slug: 'baan-kang-wat-market',
    description: 'Tucked behind Wat Suan Dok, this hidden artisan village hosts talented local craftspeople selling handmade goods every weekend. The real Chiang Mai experience.',
    category: 'market',
    subcategory: 'artisan',
    location: 'Suthep Rd, Suthep, Mueang Chiang Mai',
    latitude: 18.7878,
    longitude: 98.9618,
    images: [
      'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800',
    ],
    crowdLevel: 'MODERATE',
    averageRating: 4.7,
    totalVisitors: 8900,
    weeklyVisitors: 180,
    isApproved: true,
    isFeatured: false,
    isHiddenGem: true,
    ownerId: 'user-merchant-5',
    createdAt: '2024-01-25T08:00:00Z',
  },
  {
    id: 'store-6',
    name: 'Thai Massage Ancient Way',
    slug: 'thai-massage-ancient-way',
    description: 'Authentic traditional Thai massage by certified therapists trained at Chiang Mai's Shivagakomarpaj Traditional Medicine Hospital. Pure healing, no gimmicks.',
    category: 'spa',
    subcategory: 'massage',
    location: 'Wualai Rd, Hai Ya, Mueang Chiang Mai',
    latitude: 18.7773,
    longitude: 98.9901,
    images: [
      'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800',
    ],
    crowdLevel: 'QUIET',
    averageRating: 4.9,
    totalVisitors: 3100,
    weeklyVisitors: 45,
    isApproved: true,
    isFeatured: false,
    isHiddenGem: true,
    ownerId: 'user-merchant-6',
    createdAt: '2024-02-10T08:00:00Z',
  },
]

export const mockMissions: Mission[] = [
  {
    id: 'mission-1',
    title: 'Nimman Coffee Crawl',
    description: 'Visit 3 specialty coffee shops in the Nimman area and check in at each one. Discover the best brews the neighborhood has to offer!',
    pointsReward: 150,
    xpReward: 75,
    difficulty: 'MEDIUM',
    startDate: '2025-05-05T00:00:00Z',
    endDate: '2025-05-12T00:00:00Z',
    isDynamic: false,
    isActive: true,
    requiredCheckIns: 3,
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
    createdAt: '2025-05-01T00:00:00Z',
  },
  {
    id: 'mission-2',
    title: 'Hidden Gem Hunter',
    description: 'Find and visit a hidden gem location that most tourists never discover. Local knowledge unlocked!',
    pointsReward: 200,
    xpReward: 100,
    difficulty: 'HARD',
    startDate: '2025-05-01T00:00:00Z',
    endDate: '2025-05-31T00:00:00Z',
    targetStoreId: 'store-3',
    isDynamic: true,
    isActive: true,
    requiredCheckIns: 1,
    badgeReward: 'EXPLORER',
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400',
    createdAt: '2025-05-01T00:00:00Z',
  },
  {
    id: 'mission-3',
    title: 'Khao Soi Quest',
    description: 'Experience the authentic taste of Northern Thailand. Visit the legendary Khao Soi Lung Prakit for a real Chiang Mai food moment.',
    pointsReward: 80,
    xpReward: 40,
    difficulty: 'EASY',
    startDate: '2025-05-01T00:00:00Z',
    endDate: '2025-05-14T00:00:00Z',
    targetStoreId: 'store-2',
    isDynamic: false,
    isActive: true,
    requiredCheckIns: 1,
    badgeReward: 'FOODIE',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400',
    createdAt: '2025-05-01T00:00:00Z',
  },
  {
    id: 'mission-4',
    title: 'Night Owl Chiang Mai',
    description: 'Experience the legendary Chiang Mai nightlife! Visit 2 bars or night venues after 9 PM.',
    pointsReward: 300,
    xpReward: 150,
    difficulty: 'LEGENDARY',
    startDate: '2025-05-01T00:00:00Z',
    endDate: '2025-05-31T00:00:00Z',
    isDynamic: false,
    isActive: true,
    requiredCheckIns: 2,
    badgeReward: 'NIGHTOWL',
    imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=400',
    createdAt: '2025-05-01T00:00:00Z',
  },
  {
    id: 'mission-5',
    title: 'Market Day Adventure',
    description: 'Explore the artisan markets of Chiang Mai and discover unique handmade goods from local craftspeople.',
    pointsReward: 120,
    xpReward: 60,
    difficulty: 'EASY',
    startDate: '2025-05-01T00:00:00Z',
    endDate: '2025-05-18T00:00:00Z',
    isDynamic: false,
    isActive: true,
    requiredCheckIns: 1,
    imageUrl: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=400',
    createdAt: '2025-05-01T00:00:00Z',
  },
]

export const mockUser: User = {
  id: 'user-1',
  name: 'Alex Chen',
  email: 'alex@example.com',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100',
  level: 7,
  xp: 6200,
  points: 1450,
  streak: 12,
  role: 'CUSTOMER',
  createdAt: '2024-03-01T00:00:00Z',
}

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    userId: 'user-1',
    storeId: 'store-1',
    user: mockUser,
    rating: 5,
    comment: 'Absolutely the best specialty coffee in Chiang Mai. The baristas here are true artists. I had a natural process Ethiopian that was mind-blowing.',
    images: [],
    helpful: 24,
    createdAt: '2025-04-20T10:00:00Z',
  },
  {
    id: 'review-2',
    userId: 'user-2',
    storeId: 'store-1',
    rating: 5,
    comment: 'Perfect place to work from. Great wifi, amazing coffee, and the staff are super friendly. A must-visit for any coffee lover.',
    images: [],
    helpful: 18,
    createdAt: '2025-04-18T14:00:00Z',
  },
]

export const mockRewards: Reward[] = [
  {
    id: 'reward-1',
    title: 'Free Specialty Coffee',
    description: 'Redeem for one free specialty coffee drink of your choice at Ristr8to Lab.',
    pointsRequired: 500,
    storeId: 'store-1',
    quantity: 50,
    expiryDate: '2025-06-30T00:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
    isActive: true,
  },
  {
    id: 'reward-2',
    title: '20% Discount on Khao Soi',
    description: 'Get 20% off your next bowl of Khao Soi at Lung Prakit.',
    pointsRequired: 250,
    storeId: 'store-2',
    quantity: 100,
    expiryDate: '2025-05-31T00:00:00Z',
    isActive: true,
  },
  {
    id: 'reward-3',
    title: '60-min Thai Massage',
    description: 'Enjoy a complimentary 60-minute traditional Thai massage.',
    pointsRequired: 1200,
    storeId: 'store-6',
    quantity: 20,
    expiryDate: '2025-07-31T00:00:00Z',
    isActive: true,
  },
]

export const mockBadges: Badge[] = [
  {
    id: 'badge-1',
    type: 'EXPLORER',
    name: 'Explorer',
    description: 'Discovered 5 hidden gems around Chiang Mai',
    imageUrl: '🗺️',
    xpRequired: 500,
  },
  {
    id: 'badge-2',
    type: 'FOODIE',
    name: 'Foodie',
    description: 'Visited 10 local restaurants and reviewed them',
    imageUrl: '🍜',
    xpRequired: 300,
  },
  {
    id: 'badge-3',
    type: 'SOCIAL',
    name: 'Social Butterfly',
    description: 'Left 20 helpful reviews for the community',
    imageUrl: '🦋',
    xpRequired: 400,
  },
  {
    id: 'badge-4',
    type: 'LOYALIST',
    name: 'Loyalist',
    description: 'Maintained a 30-day check-in streak',
    imageUrl: '👑',
    xpRequired: 1000,
  },
  {
    id: 'badge-5',
    type: 'NIGHTOWL',
    name: 'Night Owl',
    description: 'Experienced Chiang Mai after dark at 5 venues',
    imageUrl: '🦉',
    xpRequired: 600,
  },
  {
    id: 'badge-6',
    type: 'PIONEER',
    name: 'Pioneer',
    description: 'First to check in at 3 new locations',
    imageUrl: '⚡',
    xpRequired: 800,
  },
]

export const mockAnalyticsData = {
  dailyTraffic: [
    { date: 'Mon', visitors: 120, checkIns: 89 },
    { date: 'Tue', visitors: 145, checkIns: 102 },
    { date: 'Wed', visitors: 98, checkIns: 71 },
    { date: 'Thu', visitors: 167, checkIns: 134 },
    { date: 'Fri', visitors: 234, checkIns: 198 },
    { date: 'Sat', visitors: 312, checkIns: 267 },
    { date: 'Sun', visitors: 289, checkIns: 241 },
  ],
  peakHours: [
    { hour: '8am', visitors: 23 },
    { hour: '9am', visitors: 45 },
    { hour: '10am', visitors: 78 },
    { hour: '11am', visitors: 92 },
    { hour: '12pm', visitors: 134 },
    { hour: '1pm', visitors: 156 },
    { hour: '2pm', visitors: 112 },
    { hour: '3pm', visitors: 98 },
    { hour: '4pm', visitors: 87 },
    { hour: '5pm', visitors: 103 },
    { hour: '6pm', visitors: 145 },
    { hour: '7pm', visitors: 189 },
    { hour: '8pm', visitors: 167 },
    { hour: '9pm', visitors: 134 },
  ],
  customerEngagement: [
    { month: 'Jan', new: 145, returning: 89 },
    { month: 'Feb', new: 167, returning: 123 },
    { month: 'Mar', new: 189, returning: 156 },
    { month: 'Apr', new: 212, returning: 178 },
    { month: 'May', new: 198, returning: 201 },
  ],
  reviewTrends: [
    { month: 'Jan', rating: 4.5, count: 23 },
    { month: 'Feb', rating: 4.6, count: 31 },
    { month: 'Mar', rating: 4.7, count: 28 },
    { month: 'Apr', rating: 4.8, count: 45 },
    { month: 'May', rating: 4.8, count: 38 },
  ],
}